### ISSUE TITLE
Tally-Timing

### ISSUE THREAD

**Issue by TobiasBecker** [qmsk/e2#14]
During my testing I found that the _new_ tally is HIGH  _after_ the e2 transition (1000ms blend).
So during the blend **only** the _old source_ is still live (that is being faded out)
but **not the new one** (although you can see a little bit from that source on program already).
_The tally light for the new source will only become active when the transition is done._

So normally with tally if you have lets say a 1s dissolve between two sources
then for this one second BOTH tallys are on.

Is this currently a limitation from the barco protocol that you cannot get this information earlier or is there another reason?

Thanks, Tobi

**Comment by SpComb** [comment]
[0.4.0](https://github.com/qmsk/e2/releases/tag/v0.4.0) adds initial support for Tally transitions, having both preview/program GPIO/Universe inputs high during an AutoTrans operation on a ScreenDest.

TODO on support for manual transitions and Web/SPI-LED drivers.

It gets tricky quickly when considering individual layer transitions, multiple screendests transitioning at different times etc, so I'm not going to call it complete yet.

**Comment by SpComb** [comment]
[0.4.1](https://github.com/qmsk/e2/releases/tag/v0.4.1) adds support for manual T-bar transitions, `--tally-color-*`options, and (animated) Web UI + SPI-LED transition colors.

**Comment by SpComb** [comment]
I think this issue can be considered done. I'm not aware of any specific cases where the tally output doesn't handle the transitions correctly, so those can be separate issues.
