### ISSUE TITLE
Ignore more than one destination

### ISSUE THREAD

**Issue by dirkdamerau** [qmsk/e2#30]
Is there a way to add more than one destination to the --tally-ignore-dest=REGEXP command ?
If I add a complete second argument :

`--tally-ignore-dest=DEST1 --tally-ignore-dest=DEST2`

only DEST2 is ignored. Dividing Destinations by "," or ";"

`--tally-ignore-dest=DEST1,DEST2`

does not work as well.

Best regards
Dirk

**Comment by SpComb** [comment]
The `--tally-ignore-dest` only accepts one regexp, but you can use a single [regexp](https://github.com/google/re2/wiki/Syntax) that matches both values: `--tally-ignore-dest='DEST1|DEST2'`.

Note the use of quotes to prevent your shell from interpreting the `|`.
