### ISSUE TITLE
options.ClientOptions.Client undefined

### ISSUE THREAD

**Issue by dougthebug** [qmsk/e2#7]
After I posted the instructions for  I realized I missed a step, and when I tried to run the command to install client I got:

> pi@raspberrypi:~/work/src/e2 $ go install ./cmd/client
> # e2/cmd/client
> 
> cmd/client/aux_list.go:15: options.ClientOptions.Client undefined (type client.Options has no field or method Client)
> cmd/client/list_destinations.go:15: options.ClientOptions.Client undefined (type client.Options has no field or method Client)
> cmd/client/preset_list.go:15: options.ClientOptions.Client undefined (type client.Options has no field or method Client)
> cmd/client/preset_show.go:17: options.ClientOptions.Client undefined (type client.Options has no field or method Client)
> cmd/client/screen_list.go:15: options.ClientOptions.Client undefined (type client.Options has no field or method Client)
> cmd/client/screen_show.go:17: options.ClientOptions.Client undefined (type client.Options has no field or method Client)
> cmd/client/source_list.go:15: options.ClientOptions.Client undefined (type client.Options has no field or method Client)

Everything else compiled but client...

**Comment by SpComb** [comment]
That's a genuine bug :)

Seems like I broke this back with ec9501d329, when I was refactoring. I haven't been using the client application much.

Really should setup that CI for build tests :)

**Comment by dougthebug** [comment]
Yay!  I'm contributing!  I'll keep breaking it if you keep fixing it!
