### ISSUE TITLE
Server (Web UI) not opening port 8002

### ISSUE THREAD

**Issue by dougthebug** [qmsk/e2#9]
Following the instructions to setting up the server, https://github.com/qmsk/e2#server-web-ui 

Port 8002 does not open.  Port 8284 is open, but none of the examples in the PNGs work. I did a port scan and only port 22 and 8284 are open.

I am unclear as to the meaning of the following line:

> Using the server Web UI requires #Building the static assets for the web fronted.

Is this the same as the earlier step of running 'bower install' inside static?

Here is the output of running the example:

> pi@raspberrypi:~/work/src/e2 $ $GOPATH/bin/server --discovery-interface=eth0 --http-listen=:8284 --http-static=./static
> 2016/09/12 19:32:34 Discovery: using interface eth0 broadcast address: 192.168.1.255
> 2016/09/12 19:32:34 Discovering systems on 192.168.1.255:40961...
> 2016/09/12 19:32:34 Discovered system: 192.168.1.27
> 2016/09/12 19:32:34 Client client.Options{Address:"192.168.1.27", JSONPort:"9999", XMLPort:"9876", TCPPort:"9878", Timeout:10000000000, Safe:false, ReadOnly:false, Debug:false, ReadKeepalive:false}: 192.168.1.27
> 2016/09/12 19:32:34 Discovery.receiver: read udp4 0.0.0.0:43285: use of closed network connection
> 2016/09/12 19:32:34 Discovery.run: stopped
> 2016/09/12 19:32:34 Client client.Options{Address:"192.168.1.27", JSONPort:"9999", XMLPort:"9876", TCPPort:"9878", Timeout:10000000000, Safe:false, ReadOnly:false, Debug:false, ReadKeepalive:false}: XMLClient: &{10000000000 0x10722740 0x10716570 <nil> 0x10714dc0 <nil> 0x10714d80 0x10714e00 false false}
> 2016/09/12 19:32:34 Client 192.168.1.27: TCPClient: 192.168.1.27
> 2016/09/12 19:32:34 Serve static /static/ from ./static
> 2016/09/12 19:32:34 client: System.Reset()
> 2016/09/12 19:32:34 XML new Source[0]
> 2016/09/12 19:32:34 XML new Source[1]
> 2016/09/12 19:32:34 XML new Source[2]
> 2016/09/12 19:32:34 XML new Source[3]
> 2016/09/12 19:32:34 XML new Source[4]
> 2016/09/12 19:32:34 XML new Source[5]
> 2016/09/12 19:32:34 XML new InputCfg[0]
> 2016/09/12 19:32:34 XML new InputCfg[1]
> 2016/09/12 19:32:34 XML new InputCfg[2]
> 2016/09/12 19:32:34 XML new InputCfg[3]
> 2016/09/12 19:32:35 XML new AuxDest[0]
> 2016/09/12 19:32:35 XML new ScreenDest[0]
> 2016/09/12 19:32:35 XML new BGLyr[0]
> 2016/09/12 19:32:35 XML new BGLyr[1]
> 2016/09/12 19:32:35 XML new Transition[0]
> 2016/09/12 19:32:35 XML new Transition[1]
> 2016/09/12 19:32:35 XML new Layer[0]
> 2016/09/12 19:32:35 XML new Layer[1]
> 2016/09/12 19:32:35 XML new Layer[2]
> 2016/09/12 19:32:35 XML new Layer[3]
> 2016/09/12 19:32:35 XML new ScreenDest[1]
> 2016/09/12 19:32:35 XML new BGLyr[0]
> 2016/09/12 19:32:35 XML new BGLyr[1]
> 2016/09/12 19:32:35 XML new Transition[0]
> 2016/09/12 19:32:35 XML new Transition[1]
> 2016/09/12 19:32:35 XML new Layer[0]
> 2016/09/12 19:32:35 XML new Layer[1]
> 2016/09/12 19:32:35 XML new Layer[2]
> 2016/09/12 19:32:35 XML new Layer[3]
> 2016/09/12 19:32:35 XML new Preset[0]
> 2016/09/12 19:32:35 XML new Preset[1]
> 2016/09/12 19:32:35 XML new Preset[2]
> 2016/09/12 19:32:35 XML new Preset[3]
> 2016/09/12 19:32:35 XML new Preset[4]
> 2016/09/12 19:32:35 XML new Frame[%!d(string=7c::c7::08::0c::cc::dc)]
> 2016/09/12 19:32:36 xmlClient.read: reset

**Comment by SpComb** [comment]
It's whatever port you set with `--http-listen=:8284`. For the screenshots I just happened to have it set to `--http-listen=:8002`.
